# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.cache/wt} [current_project]
set_property parent.project_path {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {{D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/imports/srcs/instruction_mem.mem}}
read_verilog -library xil_defaultlib -sv {
  {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/imports/srcs/ALU.sv}
  {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/imports/srcs/Branch_Condition.sv}
  {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/new/Clock_divider.sv}
  {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/imports/srcs/Controller.sv}
  {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/imports/srcs/Data_Memory.sv}
  {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/imports/srcs/Immediate_Generator.sv}
  {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/imports/srcs/Instruction_Memory.sv}
  {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/imports/srcs/Program_Counter.sv}
  {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/imports/srcs/Register_File.sv}
  {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/imports/srcs/top.sv}
  {D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/sources_1/new/top_hardware.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/constrs_1/new/PROCESSOR.xdc}}
set_property used_in_implementation false [get_files {{D:/Ubuntu/Single Cycle Hardware/Single Cycle Hardware.srcs/constrs_1/new/PROCESSOR.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_hardware -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_hardware.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_hardware_utilization_synth.rpt -pb top_hardware_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
